# Generated by Django 6.0 on 2025-12-21 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Laboratuvar Adı')),
                ('city', models.CharField(max_length=50, verbose_name='Şehir')),
            ],
        ),
        migrations.CreateModel(
            name='IrisPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.FloatField(verbose_name='Çanak Yaprak Uzunluğu (cm)')),
                ('sepal_width', models.FloatField(verbose_name='Çanak Yaprak Genişliği (cm)')),
                ('petal_length', models.FloatField(verbose_name='Taç Yaprak Uzunluğu (cm)')),
                ('petal_width', models.FloatField(verbose_name='Taç Yaprak Genişliği (cm)')),
                ('species', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tür')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iris_app.laboratory', verbose_name='İlgili Laboratuvar')),
            ],
        ),
    ]
