# Generated by Django 6.0 on 2025-12-22 13:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='irisplant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Iris Örneği', 'verbose_name_plural': 'Iris Örnekleri'},
        ),
        migrations.AlterModelOptions(
            name='laboratory',
            options={'ordering': ['name'], 'verbose_name': 'Laboratuvar', 'verbose_name_plural': 'Laboratuvarlar'},
        ),
        migrations.AddField(
            model_name='irisplant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='iris_plants', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='lab',
            field=models.ForeignKey(blank=True, help_text='Örneğin kaynağı olan laboratuvar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iris_plants', to='iris_app.laboratory', verbose_name='Laboratuvar'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='petal_length',
            field=models.FloatField(help_text='Petal yapraklarının uzunluğu', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Petal Uzunluğu (cm)'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='petal_width',
            field=models.FloatField(help_text='Petal yapraklarının genişliği', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Petal Genişliği (cm)'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='sepal_length',
            field=models.FloatField(help_text='Sepal yapraklarının uzunluğu', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Sepal Uzunluğu (cm)'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='sepal_width',
            field=models.FloatField(help_text='Sepal yapraklarının genişliği', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Sepal Genişliği (cm)'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='species',
            field=models.CharField(choices=[('setosa', 'Iris Setosa'), ('versicolor', 'Iris Versicolor'), ('virginica', 'Iris Virginica')], default=django.utils.timezone.now, help_text='Iris bitki türü', max_length=50, verbose_name='Tür'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Laboratuvar Adı'),
        ),
        migrations.AddIndex(
            model_name='irisplant',
            index=models.Index(fields=['species'], name='iris_app_ir_species_9b8003_idx'),
        ),
        migrations.AddIndex(
            model_name='irisplant',
            index=models.Index(fields=['created_at'], name='iris_app_ir_created_c03841_idx'),
        ),
    ]
