# Generated by Django 6.0 on 2025-12-22 17:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0002_alter_irisplant_options_alter_laboratory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='country',
            field=models.CharField(default='Turkey', max_length=50, verbose_name='Ülke'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='established_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kuruluş Yılı'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='created_by',
            field=models.ForeignKey(help_text='Bu kaydı oluşturan kullanıcı', on_delete=django.db.models.deletion.CASCADE, related_name='iris_plants', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='lab',
            field=models.ForeignKey(blank=True, help_text='Bu örneğin kaynağı olan laboratuvar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iris_plants', to='iris_app.laboratory', verbose_name='Laboratuvar'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='petal_length',
            field=models.FloatField(help_text='Petal yapraklarının uzunluğu (santimetre cinsinden)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Petal Uzunluğu (cm)'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='petal_width',
            field=models.FloatField(help_text='Petal yapraklarının genişliği (santimetre cinsinden)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Petal Genişliği (cm)'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='sepal_length',
            field=models.FloatField(help_text='Sepal yapraklarının uzunluğu (santimetre cinsinden)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Sepal Uzunluğu (cm)'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='sepal_width',
            field=models.FloatField(help_text='Sepal yapraklarının genişliği (santimetre cinsinden)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Sepal Genişliği (cm)'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='species',
            field=models.CharField(choices=[('setosa', 'Iris Setosa'), ('versicolor', 'Iris Versicolor'), ('virginica', 'Iris Virginica')], help_text='Iris bitki türü (setosa, versicolor veya virginica)', max_length=50, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AddIndex(
            model_name='irisplant',
            index=models.Index(fields=['created_by'], name='iris_app_ir_created_77cd75_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratory',
            index=models.Index(fields=['name'], name='iris_app_la_name_c373b0_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratory',
            index=models.Index(fields=['city'], name='iris_app_la_city_73f1df_idx'),
        ),
    ]
