# Generated by Django 6.0 on 2025-12-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0003_laboratory_country_laboratory_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratory',
            old_name='email',
            new_name='email_test',
        ),
    ]
