# Generated by Django 6.0 on 2025-12-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0004_rename_email_laboratory_email_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratory',
            old_name='email_test',
            new_name='email',
        ),
    ]
