# Generated by Django 6.0 on 2025-12-23 14:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0005_rename_email_test_laboratory_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='irisplant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Iris Sample', 'verbose_name_plural': 'Iris Samples'},
        ),
        migrations.AlterModelOptions(
            name='laboratory',
            options={'ordering': ['name'], 'verbose_name': 'Laboratory', 'verbose_name_plural': 'Laboratories'},
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.CASCADE, related_name='iris_plants', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='lab',
            field=models.ForeignKey(blank=True, help_text='Source laboratory of this sample', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iris_plants', to='iris_app.laboratory', verbose_name='Laboratory'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='petal_length',
            field=models.FloatField(help_text='Length of the petal (in cm)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Petal Length (cm)'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='petal_width',
            field=models.FloatField(help_text='Width of the petal (in cm)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Petal Width (cm)'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='sepal_length',
            field=models.FloatField(help_text='Length of the sepal (in cm)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Sepal Length (cm)'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='sepal_width',
            field=models.FloatField(help_text='Width of the sepal (in cm)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Sepal Width (cm)'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='species',
            field=models.CharField(choices=[('setosa', 'Iris Setosa'), ('versicolor', 'Iris Versicolor'), ('virginica', 'Iris Virginica')], help_text='Iris plant species (setosa, versicolor or virginica)', max_length=50, verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='country',
            field=models.CharField(default='Turkey', max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='established_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Established Year'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Laboratory Name'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
